### ISSUE TITLE
Cannot get test data

### ISSUE THREAD

**Issue by rougier** [heilerich/neurone_loader#6]
After having cloned and made a user install, I tried to get the data (from `tests/get_test_data.sh`) but it failed:

```
Cloning into 'NeuroneTestdata'...
warning: redirecting to https://gin.g-node.org/heilerich/NeuroneTestdata/
remote: Enumerating objects: 251, done.
remote: Counting objects: 100% (251/251), done.
remote: Compressing objects: 100% (194/194), done.
remote: Total 251 (delta 86), reused 0 (delta 0)
Receiving objects: 100% (251/251), 86.46 KiB | 614.00 KiB/s, done.
Resolving deltas: 100% (86/86), done.
find: wget: No such file or directory
...
find: wget: No such file or directory
```

Any idea ?

**Comment by heilerich** [comment]
The script uses [wget](https://www.gnu.org/software/wget/) to download the files. This looks like you haven’t installed it. I should probably put that in the README.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rougier** [comment]
Call me stupid! I was so sure it was installed that I thought the missing file was referring to something else... Sorry.
